# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
name: 091.4-deploy-azure-resource
on:
  push:
    branches: [none]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      dev:
        description: "Deploy dev environment"
        required: false
        default: true
        type: boolean
      test:
        description: "Deploy test environment"
        required: false
        default: false
        type: boolean
      prod:
        description: "Deploy prod environment"
        required: false
        default: false
        type: boolean

jobs:
  prepare-infra:
    runs-on: ubuntu-latest
 
    if: ${{ (inputs.dev)}}
    steps:
      - uses: actions/checkout@v3

      - name: Az CLI login
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      - name: Validate subscription-scope Bicep
        run: |
          az deployment sub validate \
            --location westus3 \
            --template-file infra2/main.bicep \
            --parameters infra2/main-dev.bicepparam

      - name: Preview subscription-scope Bicep changes
        run: |
          az deployment sub what-if \
            --location westus3 \
            --template-file infra2/main.bicep \
            --parameters infra2/main-dev.bicepparam

  deploy-infra:
    needs: prepare-infra
    runs-on: ubuntu-latest
 
    if: ${{ (inputs.dev)}}
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Echo Script
        run: |
          echo "starting deploy for ${{ matrix.environment }}"

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      - name: Deploy the bicep script
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          scope: "subscription"
          region: "westus3"
          template: "infra2/main.bicep"
          parameters: "infra2/main-dev.bicepparam"
